name: CMake

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Install libraries (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install -y cmake libasio-dev libasan8

      - name: Install libraries (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install asio libiconv

          cat << EOF > nproc
          #!/bin/sh
          sysctl -n hw.logicalcpu
          EOF
          chmod a+x nproc
          sudo cp nproc /usr/local/bin/nproc
          rm -f nproc

      - name: Install phosg
        run: |
          git clone https://github.com/fuzziqersoftware/phosg.git
          cd phosg
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} .
          make -j $(nproc)
          sudo make install

      - name: Install resource_file
        run: |
          git clone https://github.com/fuzziqersoftware/resource_dasm.git
          cd resource_dasm
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} .
          make -j $(nproc)
          sudo make install

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} -j $(nproc)

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure
